// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.API.Data;

namespace SmartSchool.API.Data.Migrations
{
    [DbContext(typeof(SmartSchoolContext))]
    partial class SmartSchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartSchool.API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFimMatricula")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicioMatricula")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataInicioMatricula = new DateTime(2020, 10, 12, 20, 28, 32, 173, DateTimeKind.Local).AddTicks(4793),
                            DataNascimento = new DateTime(2000, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "+551122223333"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataInicioMatricula = new DateTime(2020, 10, 12, 20, 28, 32, 174, DateTimeKind.Local).AddTicks(1451),
                            DataNascimento = new DateTime(2000, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "+551133334444"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataInicioMatricula = new DateTime(2020, 10, 12, 20, 28, 32, 174, DateTimeKind.Local).AddTicks(1512),
                            DataNascimento = new DateTime(2002, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "+551144445555"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataInicioMatricula = new DateTime(2020, 10, 12, 20, 28, 32, 174, DateTimeKind.Local).AddTicks(1518),
                            DataNascimento = new DateTime(1998, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "+551155556666"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataInicioMatricula = new DateTime(2020, 10, 12, 20, 28, 32, 174, DateTimeKind.Local).AddTicks(1522),
                            DataNascimento = new DateTime(2001, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "+551166667777"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataInicioMatricula = new DateTime(2020, 10, 12, 20, 28, 32, 174, DateTimeKind.Local).AddTicks(1529),
                            DataNascimento = new DateTime(2003, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "+551177778888"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataInicioMatricula = new DateTime(2020, 10, 12, 20, 28, 32, 174, DateTimeKind.Local).AddTicks(1533),
                            DataNascimento = new DateTime(2005, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "+551188889999"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            CursoId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8096)
                        },
                        new
                        {
                            AlunoId = 2,
                            CursoId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8563)
                        },
                        new
                        {
                            AlunoId = 3,
                            CursoId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8581)
                        },
                        new
                        {
                            AlunoId = 4,
                            CursoId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8583)
                        },
                        new
                        {
                            AlunoId = 5,
                            CursoId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8584)
                        },
                        new
                        {
                            AlunoId = 6,
                            CursoId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8585)
                        },
                        new
                        {
                            AlunoId = 7,
                            CursoId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8586)
                        },
                        new
                        {
                            AlunoId = 1,
                            CursoId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8587)
                        },
                        new
                        {
                            AlunoId = 2,
                            CursoId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8588)
                        },
                        new
                        {
                            AlunoId = 3,
                            CursoId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8589)
                        },
                        new
                        {
                            AlunoId = 4,
                            CursoId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8590)
                        },
                        new
                        {
                            AlunoId = 5,
                            CursoId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8592)
                        },
                        new
                        {
                            AlunoId = 6,
                            CursoId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8593)
                        },
                        new
                        {
                            AlunoId = 7,
                            CursoId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8594)
                        },
                        new
                        {
                            AlunoId = 1,
                            CursoId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8595)
                        },
                        new
                        {
                            AlunoId = 2,
                            CursoId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8596)
                        },
                        new
                        {
                            AlunoId = 3,
                            CursoId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8597)
                        },
                        new
                        {
                            AlunoId = 4,
                            CursoId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8598)
                        },
                        new
                        {
                            AlunoId = 5,
                            CursoId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8599)
                        },
                        new
                        {
                            AlunoId = 6,
                            CursoId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8601)
                        },
                        new
                        {
                            AlunoId = 7,
                            CursoId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(8602)
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(6636)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7131)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7149)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7150)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7152)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7155)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7156)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7157)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7158)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7161)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7162)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7164)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7165)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7166)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7167)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7168)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7170)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7172)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7173)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7174)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7175)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7177)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            DataInicio = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(7178)
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("PreRequisitoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PreRequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 200,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 400,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 450,
                            CursoId = 3,
                            Nome = "Física",
                            PreRequisitoId = 2,
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 100,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 150,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 150,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CargaHoraria = 250,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 480,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CargaHoraria = 420,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 420,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFimRegistro")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicioRegistro")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("Registro")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataInicioRegistro = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(943),
                            Nome = "Lauro",
                            Registro = 1,
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataInicioRegistro = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(1990),
                            Nome = "Roberto",
                            Registro = 2,
                            Sobrenome = "Soares"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataInicioRegistro = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(2028),
                            Nome = "Ronaldo",
                            Registro = 3,
                            Sobrenome = "Marconi"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataInicioRegistro = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(2030),
                            Nome = "Rodrigo",
                            Registro = 4,
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataInicioRegistro = new DateTime(2020, 10, 12, 20, 28, 32, 175, DateTimeKind.Local).AddTicks(2031),
                            Nome = "Alexandre",
                            Registro = 5,
                            Sobrenome = "Montanha"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.AlunoCurso", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.API.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.API.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Models.Disciplina", "PreRequisito")
                        .WithMany()
                        .HasForeignKey("PreRequisitoId");

                    b.HasOne("SmartSchool.API.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
